export const DIGITAL_FORM_REPOSITORY = Symbol('DIGITAL_FORM_REPOSITORY');
export const DIGITAL_FORM_SERVICE = Symbol('DIGITAL_FORM_SERVICE');

// Tokens for specialized services
export const DIGITAL_FORM_CORE_SERVICE = Symbol('DIGITAL_FORM_CORE_SERVICE');
export const DIGITAL_FORM_ENTRY_SERVICE = Symbol('DIGITAL_FORM_ENTRY_SERVICE');
export const DIGITAL_FORM_WORKFLOW_SERVICE = Symbol(
  'DIGITAL_FORM_WORKFLOW_SERVICE',
);
export const DIGITAL_FORM_REPORT_SERVICE = Symbol(
  'DIGITAL_FORM_REPORT_SERVICE',
);
export const DIGITAL_FORM_EXPORT_SERVICE = Symbol(
  'DIGITAL_FORM_EXPORT_SERVICE',
);

export const DIGITAL_FORM_SCHEDULER = Symbol('DIGITAL_FORM_SCHEDULER');
