version: '3'

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres-daily-performance
    restart: always
    ports:
      - "5432:5432" #Run on port 5433 to avoid conflict with local postgres
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=tbsgroup@123
      - POSTGRESQL_DATABASE=daily_performance
    networks:
      - social
  redis:
    image: redis:latest
    container_name: tbsgroup-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    environment:
      - REDIS_PASSWORD=tbsgroup@123
    networks:
      - social
    command: sh -c "redis-server --appendonly yes --requirepass \"$${REDIS_PASSWORD}\""
networks:
  social:


volumes:
  daily_performance_mysql:
  redis-data:
