export const POST_LIKE_REPOSITORY = Symbol('POST_LIKE_REPOSITORY');
export const POST_LIKE_SERVICE = Symbol('POST_LIKE_SERVICE');
export const POST_QUERY_REPOSITORY = Symbol('POST_QUERY_REPOSITORY');
