export const FORM_SETTINGS_REPOSITORY = Symbol('FORM_SETTINGS_REPOSITORY');
export const FORM_SETTINGS_SERVICE = Symbol('FORM_SETTINGS_SERVICE');
export const FORM_SETTINGS_CONTROLLER = Symbol('FORM_SETTINGS_CONTROLLER');
